---
title: "Comparing"
author: "Julian Bernado"
date: "2024-10-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importing libraries
set.seed(525600)
library(dplyr)
library(optmatch)
library(RItools)

df <- generate_multilevel_data(10, 100, p = 4) %>% assign_treatment()
matching <- pairmatch(Treatment ~ X1 + X2 + X3 + X4, data = df)
pre_bt <- balanceTest(Treatment ~ X1 + X2 + X3 + X4, data = df)
bt <- balanceTest(Treatment ~ X1 + X2 + X3 + X4 + strata(matching), data = df)
pre_bt
bt
```

```{r}
generate_multilevel_data <- function(S, Ns, p, gsd = 10, ssd = 1){
  # First, initialize the group structure
  unique_groups <- 1:S
  groupmeans <- rnorm(S, mean = 0, sd = gsd)
  if(length(Ns) == 1){
    Ns <- rep(Ns, S)
  }
  N <- sum(Ns)
  assigned_groups <- numeric()
  for(i in 1:S){
    assigned_groups <- c(assigned_groups, rep(i, Ns[i]))
  }
  assigned_groups <- as.factor(assigned_groups)
  
  # Now, initialize the member level structure within groups
  X <- matrix(rnorm(N*p, mean = 0, sd = 1), nrow = N, ncol = p)
  beta <- matrix(rnorm(p, mean = 0, sd = 1), nrow = p)
  member_outcomes <- numeric()
  for(i in 1:S){
    group_member_outcomes <- rnorm(Ns[i], mean = X %*% beta + groupmeans[i], sd = ssd)
    member_outcomes <- c(member_outcomes, group_member_outcomes)
  }
  
  # Combine covariates and proceed
  colnames(X) <- paste0("X", 1:p)
  design <- as_tibble(X) %>%
    mutate(Y = member_outcomes) %>%
    mutate(Group = assigned_groups) %>%
    relocate(Y, Group)
  
  return(design)
}

assign_treatment <- function(df,  Nt = NULL){
  N <- nrow(df)
  S <- df %>%
    pull(Group) %>%
    unique() %>%
    length()
  if(is.null(Nt)){
    Nt = as.integer(S/2)
  }
  treatment <- rep(1, Nt)
  control <- rep(0, S - Nt)
  treatment_assignment <- sample(c(treatment, control))
  return(df %>% mutate(Treatment = if_else(treatment_assignment[as.integer(Group)] == 1, 1, 0)) %>% relocate(Y, Treatment))
}

#df <- generate_multilevel_data(S = 8000, Ns = 625, p = 2) %>%
#  assign_treatment() %>%
#  as.data.frame()

#test_match <- matchMulti(data = df,
#           treatment = "Treatment",
#           school.id = "Group",
#           student.vars = c("X1", "X2"))


#test_match$school.match
```

Broadly:
1. Make grouped version of all unit level outcomes
2. Fit a group and unit-level model
3. Get scores for all group-level models
4. Extract a standard error of the school-level model
5. Calculate a school-level caliper
6. Calculate a student-level caliper
7. For all schools falling within a caliper of each other, get proportion of students within student-caliper

To-Do: 


```{r}
group_distances <- function(data, grouping, group_level, unit_level, outcome){
  design_df <- make_grouped(data, grouping, group_level, unit_level, outcome)
  outcome_models <- model_outcomes(data, grouping, group_level, unit_level, outcome)
  group_model <- outcome_models[["group"]]
  unit_model <- outcome_models[["unit"]]
  group_se <- get_se(group_model)
  student_se <- get_se(student_model)
  calipers <- calc_caliper(group_model, student_model)
  group_pairs <- in_caliper(data, grouping, group_model, calipers[["group"]])
  pair_distances <- get_distances(group_pairs, design_df, calipers[["unit"]])
  return(group_pairs %>% mutate(matchability = pair_distances))
}
```

```{r}
# # Load Catholic school data
 data(catholic_schools)

# 
 student.cov <- c('minority','female','ses')
# 
# # Check balance student balance before matching
df <- as.data.frame(df)
balanceTable(catholic_schools[c(student.cov,'sector')],  treatment = 'sector')
balanceTable(df[c("X1", "X2", "Treatment")], treatment = "Treatment")
??matchMulti
 # 
# #Match schools but not students within schools
# match.simple <- matchMulti(catholic_schools, treatment = 'sector',
# school.id = 'school', match.students = FALSE)
# 
# #Check balance after matching - this checks both student and school balance
# balanceMulti(match.simple, student.cov = student.cov)
# 
# #Estimate treatment effect
# output <- matchMultioutcome(match.simple, out.name = "mathach",
# schl_id_name = "school",  treat.name = "sector")
# 
# # Perform sensitivity analysis using Rosenbaum bound -- increase Gamma to increase effect of
# # possible hidden confounder          
# matchMultisens(match.simple, out.name = "mathach",
#           schl_id_name = "school", 
#           treat.name = "sector", Gamma = 1.3)
#           
# 
# # Now match both schools and students within schools          
# match.out <- matchMulti(catholic_schools, treatment = 'sector',
# school.id = 'school', match.students = TRUE, student.vars = student.cov)
# 
# # Check balance again
# bal.tab <- balanceMulti(match.out, student.cov = student.cov)
# 
# # Now match with fine balance constraints on whether the school is large 
# # or has a high percentage of minority students
# match.fb <- matchMulti(catholic_schools, treatment = 'sector', school.id = 'school', 
# match.students = TRUE, student.vars = student.cov, 
# school.fb = list(c('size_large'),c('size_large','minority_mean_large')))
# 
# # Estimate treatment effects
# matchMultioutcome(match.fb, out.name = "mathach", schl_id_name = "school",  treat.name = "sector")
# 
# #Check Balance
# balanceMulti(match.fb, student.cov = student.cov)
# 
# ## End(Not run)

df <- generate_multilevel_data(S = 5, Ns = c(1, 80, 42, 2, 4), p = 2) %>%
  assign_treatment()
```

```{r}
source("../scripts/make_grouped.R")
source("../scripts/model_outcomes.R")
df <- generate_multilevel_data(S = 5, Ns = c(1, 80, 42, 2, 4), p = 7) %>% assign_treatment()
df<-as.data.frame(df)
rownames(df) <- 1:length(df$X1)


outer(df[1:10, "X1"], df[4:141, "X3"], FUN = function(x, y) return((x - y)^2))

newdf <- make_grouped(df, grouping = "Group", group_level = c("X4", "X5"), unit_level = c("X1", "X2", "X3"), outcome = "Y")
damodel <- model_outcomes(data = newdf,
                          outcome = "Y",
                          grouping = "Group")

```
